package rational.enums;

public enum SpecialRuleTypeEnum{
    ALWAYS_STRIKE_FIRST, ALWAYS_STRIKE_LAST, COLD_BLOODED, MARTIAL_PROWESS, FIGHT_IN_EXTRA_RANKS,
    PREDATORY_FIGHTER, STUBBORN, MONSTROUS_INFANTRY, AUTO_WOUND, NO_ARMOR_SAVE, NO_WARD_SAVE, FLAMING_ATTACKS, WHEN_CHARGING,
    SCURRY_AWAY, STRENGTH_IN_NUMBERS, SWIFTSTRIDE, POISONED_ATTACKS, ARMOR_PIERCING, EXTRA_ATTACKS;
}
