package rational.enums;

public enum UpgradeTypeEnum {
    WEAPON, ARMOR, MOUNT, SPECIFIC_ITEM, CUSTOM_ITEMS, SPECIAL_RULE, UNIT, WIZARD_LEVEL, CHAMPION,
    MUSICIAN, STANDARD_BEARER, MAGIC_STANDARD, BATTLE_STANDARD_BEARER,
}
