package rational;

public enum SpecialRuleTypeEnum{
    ALWAYS_STRIKE_FIRST, ALWAYS_STRIKE_LAST, COLD_BLOODED, MARTIAL_PROWESS, FIGHT_IN_EXTRA_RANKS,
    PREDATORY_FIGHTER, STUBBORN, MONSTEROUS_INFANTRY;
}
